[browser]
gatherUsageStats = false

[server]
headless = false
port = 8501

[theme]
base = "dark"
primaryColor = "#3DDC97"
backgroundColor = "#0E141B"
secondaryBackgroundColor = "#17202B"
textColor = "#E8EEF5"
font = "sans serif"
