[browser]
gatherUsageStats = false

[server]
headless = false
port = 8501

[theme]
base = "dark"
primaryColor = "#00E699"
backgroundColor = "#101214"
secondaryBackgroundColor = "#121316"
textColor = "#E8EEF5"
font = "sans serif"
